apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
  labels:
    role: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: prod
        formateur: Frazer
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
