apiVersion: v1
kind: Pod
metadata:
  name: red-pod
  labels:
    app: web
    env: prod
    formation: Frazer
spec:
  containers:
    - image: kodekloud/webapp-color
      name: webappcolor
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: red
